name: Build (Windows Only)

on:
  push:
    branches: [ main, experimental ]
  pull_request:
    branches: [ main, experimental ]
  workflow_dispatch:

jobs:
  buildWindows:
    runs-on: windows-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4.1.7

      - name: Set up Haxe
        uses: krdlab/setup-haxe@master
        with:
          haxe-version: 4.3.4

      - name: Create haxelib directory and setup
        run: |
          mkdir "%USERPROFILE%\haxelib"
          haxelib setup "%USERPROFILE%\haxelib"
        shell: cmd

      - name: Install Haxelibs and Run Setup
        run: |
          haxelib install hxcpp
          if exist setup\windows.bat call setup\windows.bat
        shell: cmd

      - name: Skip SScript Setup Mode
        run: echo oy9:showMacroty8:loopCosti25y10:includeAllfg >> %USERPROFILE%\settings.cocoa
        shell: cmd

      - name: Create Version Tag
        run: echo ${{ github.run_id }} > VERSION

      - name: Compile Windows Build
        run: haxelib run lime build windows --app-version="4.0.0-${{ github.run_id }}" -D officialBuild

      - name: Upload Windows Build Artifact
        uses: actions/upload-artifact@v4.3.4
        with:
          name: windowsBuild
          path: export/release/windows/bin
